# Generated by Django 3.1.5 on 2021-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=70)),
                ('Cholesterol', models.BooleanField(default=False)),
                ('Bp_high', models.BooleanField(default=False)),
                ('Bp_low', models.BooleanField(default=False)),
                ('Pcos_Pcod', models.BooleanField(default=False)),
                ('Diabetes', models.BooleanField(default=False)),
                ('Cold', models.BooleanField(default=False)),
            ],
        ),
    ]
