# Generated by Django 3.1.5 on 2021-04-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Cholesterol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='High_BP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Low_BP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Non',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='Pcos_Pcod',
            field=models.BooleanField(default=False),
        ),
    ]
