# Generated by Django 3.1.5 on 2021-04-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210416_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
