# Generated by Django 3.1.5 on 2021-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('totalfat', models.IntegerField()),
                ('Saturatedfat', models.IntegerField()),
                ('Sodium', models.IntegerField()),
                ('TotalCarbohydrate', models.IntegerField()),
                ('DietaryFiber', models.IntegerField()),
                ('Sugar', models.IntegerField()),
                ('Protein', models.IntegerField()),
                ('VitaminD', models.IntegerField()),
                ('Calcium', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('Potassium', models.IntegerField()),
            ],
        ),
    ]
