# Generated by Django 3.1.5 on 2021-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dataitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='item',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
